version: '3.3'

services:
  mybatis-mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "20010:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mybatis
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123456
  demo-springboot-docker:
    container_name: springboot
    image: miaosha/miaosha
    depends_on:
      - mybatis-mysql
    ports:
      - 8088:8080
    environment:
      - DATABASE_HOST=mybatis-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=mybatis
      - DATABASE_PORT=3306
