mybatis:
    mapperLocations: classpath:mapping/*.xml
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: woshicjj110
        schema: classpath:miaosha.sql
    redis:
        host: 127.0.0.1
        port: 6379
        database: 10
        jedis:
            pool:
                max-active: 50
                min-idle: 20
server:
    tomcat:
        accept-count: 1000
        max-threads: 800
        min-spare-threads: 100
---
spring:
    profiles: container
    datasource:
        url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
        schema: classpath:miaosha.sql
        initialize: true